### ISSUE TITLE
Add the ability to use the 'language' parameter

### ISSUE THREAD

**Issue by benjam-es** [thephpleague/omnipay-sagepay#102]
Are there any plans to allow the 'Language' parameter (possibly using 'localeCode' in the same way the paypal gateway does)?

This is useful for multilanguage websites

**Comment by judgej** [comment]
Good point. Not got time to finish it off today (or maybe this week) but check out the https://github.com/thephpleague/omnipay-sagepay/tree/issue102 branch. You can use the `language` parameter to set the language using the ISO639 aplha-2 code (e.g. `gb` or `GB`), or even a locale (e.g. `de-DE`).

This is a branch from `master`, which is aliased to Omnipay version 3.x.

Let me know if this works for you, port the changes to 2,x if you want, and I'll finish it off and document it.

**Comment by benjam-es** [comment]
Sorry, just noticed your reply after creating a pull request.

**Comment by judgej** [comment]
No problem, we can merge the best bits of each :-)

Just a tip on PRs: try to keep formatting and typos separate from functional changes. Both are great and just as important, but it means non-functional changes can be merged in with no effort and no dependencies, and are not held back by tweaks to functional changes. And if a functional change needs to be reversed due to some unforeseen effects later, then we don't end up reversing all the formatting. Both good though :-)

**Comment by benjam-es** [comment]
Thanks. I have tried out your new branch, but the payment pages are not yet displaying in the requested language. I have contacted sagepay for them to check to see if it is an issue at their end.

**Comment by judgej** [comment]
I've not tried it end-to-end yet - just created a test to check the `Language` field is in the data that is sent for both Direct and Server APIs.

**Comment by benjam-es** [comment]
Change the sagepay template back to the default one - and this worked. Thanks.

I look forward to the 3.0.x release.

**Comment by judgej** [comment]
This is now released as version `3.0.1`. Could you please close this issue when you are happy it is working  as expected. I have a bit of refactoring to do here next (some traits to reduce duplication of methods) but is would be nice to see this completely closed first. Thank you :-)
