### ISSUE TITLE
vat amount not send to sage pay request

### ISSUE THREAD

**Issue by arnavdots** [thephpleague/omnipay-sagepay#138]
sagepay - omnipay plugin for laravel and facing an issue regarding sending order data into sagepay basket. All data is going well except the VAT amount/ tax code.

We’re adding data into the basket using ItemBag Class and setting below fields:-

setProductCode => E8 (sage 50 isn’t reading this field as well, unfortunately we need to put it in the name field like this name => "[E8] storage pod")

name => XXXX

description => XXXX (sage 50 isn’t reading this field as well, we also need to send description in the name field)

quantity => 1

price => 1343

vat => 45 (this isn’t showing in Sagepay and it shows like 00, screenshot attached)

all fields going out into basket except VAT field.

**Comment by judgej** [comment]
Couple of things to check.

Firstly, are you using the extended `Item` class https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Extend/Item.php ? This supports VAT (though check the documentation on the format you need to supply). It also supports the product code as a separate field, instead of adding it to the description.

However, there are two basket formats: CSV and XML. Sage's products are not as joined up as people would like to hope, so it is possible one basket format works for integration with some accounting products and not others. By default the XML basket is used, but you can go back to the older CSV format by setting the `useOldBasketFormat` option.

**Comment by judgej** [comment]
No response - closing.
