### ISSUE TITLE
Issue with VendorTxCode in Server completePurchase

### ISSUE THREAD

**Issue by Jmz** [thephpleague/omnipay-sagepay#22]
I'm not sure if I've misunderstood what I'm supposed to be passing to completePurchase but the current code doesn't work for me.

I save the value of json_encode($response->getData()); before sending the user to SagePay and then pass this as the transactionReference to completePurchase. Then ServerCompleteAuthorizeRequest->getData() json_decodes the value of transactionReference but VendorTxCode is not passed back in this request from SagePay so $reference['VendorTxCode'] is always null and the signature won't match the VPSSignature from SagePay. 

I replaced line 21 in Message/ServerCompleteAuthorizeRequest.php with $this->getTransactionId() (also passed to completePurchase) which fixes the issue for me. 

I suppose another solution would be to append the VendorTxCode to the array I get from SagePay before saving it in the database.

**Comment by judgej** [comment]
What you save in the database for checking against the notification callback, is transactionReference() and you index that against your transactionId.

In OmniPay, the transaction reference is the ID that the remote gateway gives to your transaction, while transaction ID is your local ID for it. What OmniPay does, is stick *three* fields into transactionReference as a JSON array. These fields are:

VendorTxCode - your transaction ID again
VPSTxId - SagePay's transaction reference
SecurityKey - a one-use hash used to check the validity of the callback

In your callcack handler, you get the VendorTxCode from POST data and look up the transaction reference you saved. Pass that reference (the JSON string) to OmniPay, and OmniPay will then decode that and do a hash check, including all the other POST data that has been sent. If it does not match when you do a sendData() then you get an exception.

That's the core of what happens. You don't need to do any JSON manipulation - just treat the transactionReference as a string that OmniPay gives you when you initiate the transaction, and that you give it back in the callback notification.

**Comment by judgej** [comment]
See if this network flow diagram helps at all:

https://github.com/judgej/omnipay-sagepay/tree/patch-1/docs

**Comment by judgej** [comment]
Just to clear this off, in the notify handler, you get the Transaction ID using `$_POST['VendorTxCode']` then use that to look up the Transaction Reference that you saved before sending the user off to Sage Pay to enter their card details.

The request message is fetched using:

~~~php
$requestMessage = $gateway->completePurchase([
    'transactionId' => $transactionId, // SEE NOTE BELOW
    'transactionReference' => $transactionReference,
]);
~~~

Note that the transactionId is also embedded within in the transactionReference, and it is that which is used by the driver. However, if you do not pass it in here, then you get a validation error. I believe that is a bug and the [validation should be removed](https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/ServerCompleteAuthorizeRequest.php#L25).

You then `send()` that message to validate the authorisation result. That may raise an exception if validation fails, otherwise your return by calling `$responseMessage->confirm($finalUrl)` or `$responseMessage->invalid($finalUrl, $message)`

I've put a demo together here:

https://github.com/academe/OmniPay-SagePay-Demo/blob/master/sagepay-confirm.php

**Comment by judgej** [comment]
Just a note: the validation check on `transactionId` in the `CompleteRequest` class has been removed, so the `transactionId` in the previous comment no longer needs to be passed in.

I don't think there is an problem here, so I am going to close this issue, but please reopen if you think it is still not clear or is wrong.
