### ISSUE TITLE
Use of returnUrl() instead of notifyUrl()

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay-sagepay#40]
The `notifyUrl()` is for informing the remote gateway about where to notify the merchant site about the results. The `returnUrl()` is where to send the user after they have visited the gateway site. This driver uses `returnUrl()` when it means `notifyUrl()`.

We can have both running in parallel until V3.0, with `returnUrl()` deprecated.

**Comment by coatesap** [comment]
Do we know if this is going to be the accepted Omnipay standard going forwards? I'd really like to be able to separate out purely server-to-server notification URLs from customer return URLs across all the drivers we use, and this does sound like the only sensible option...

**Comment by judgej** [comment]
That would be good. These URLs that are passed to the remote gateway (return, cancel, notify) are all callbacks, some of which are used to send the user to (sometimes by GET and sometimes by POST) and some of which are used as a back-channel to communicate results. The difficulty I'm having, is just being able to get a good overview of all the gateways to compare, i.e. what URLs they use, and for what purposes.

**Comment by coatesap** [comment]
Agreed, it's not easy. I was actually planning to submit a PR for updating the WorldPay driver to use notifyUrl (with backwards compatibility, as you did for Authorize.net), as once again, their callback is actually a server-to-server notification, rather than a customer return.

I know @kayladnls was talking about updating the documentation for developers to give guidance about how to develop drivers, but at the moment, as far as I can see, it's just a few paragraphs on http://omnipay.thephpleague.com/gateways/build-your-own/.

I don't think it needs to be anything massive, but what would be massively helpful is an official guidance document for developers creating new drivers that covers some basics like:
 - The difference betweeen transactionId and transactionReference
 - The difference between returnUrl and notifyUrl
 - Encourage the use of `->validate()` before making requests

**Comment by kayladnls** [comment]
Those pages live on this branch: https://github.com/thephpleague/omnipay/tree/gh-pages Any PRs would be very welcome.

**Comment by coatesap** [comment]
Oh - that's good to know - I spent ages looking for a public repo for the docs this morning!

**Comment by judgej** [comment]
Fixed in PR #69 - supports `notifyUrl`. You can still use `returnUrl` for legacy purposes, but `notifyUrl` is more correct, and so is easier to automate (i.e. an application using this gateway knows what `notifyUrl` is).
