### ISSUE TITLE
3DSecure not working in testing environment

### ISSUE THREAD

**Issue by beningreenjam** [thephpleague/omnipay-sagepay#47]
Hi,

I'm working with Laravel 5.1 and have noticed a strange behaviour regarding 3D Secure.

Firstly, on test cards that are meant to be accepted, it's not accepting the password of "password" as instructed by SagePay.

Secondly, on cards that are meant to fail the 3D Secure authentication, it's blindly accepting them regardless of me leaving the `apply3DSecure` parameter as it's default value of `0` or not.

**Comment by judgej** [comment]
Which driver are you using - Server or Direct?

With Direct, your server needs to send the user to the 3D Secure acsUrl, but presumably with Server you don't need to worry about redirection since you have already sent the user off-site (to the Sage Pay server) anyway.

I've been working with the new REST API, and that does accept "password" as the 3DSecure pass code. That API, I understand, is implemented as a layer over the Direct API at the Sage Pay end.

Just for some context, Apply3DSecure values are:

* 0: Use the default setting on the Sage Pay System
* 1: Force 3D-Secure checks and use appropriate rules
* 2: Force NO CHECKS for this transaction and always gain and authorisation
* 3: Force 3D-Secure checks but DO NOT apply rules and always gain an authorisation

I've not needed to use 3D Secure with SagePay Direct before, but will help out where I can.

**Comment by beningreenjam** [comment]
It's the Direct integration driver. I currently have my server successfully redirecting to the ascUrl, which I believe shows an iframe for the 3D Secure form, so as it's not working for me I may need to contact SagePay regarding that specific issue.

As for the successfully authorised cards that are supposed to fail, I'm still a little lost. I have already set the value of `apply3DSecure` to both `0` and `1` as well left it out of my call to the package completely, which should keep it as the default value of `0`.

For the sake of clarification, I'm testing locally on my linux PC if that might make any difference?

**Comment by judgej** [comment]
I have a hunch there may have been some changes with SagePay here. I raised an issue with them a few weeks ago concerning some of those test cards not do what was expected. If you [check out this section](https://test.sagepay.com/documentation/#test-card-details) there is a list of cards with different results, but no mention of 3DSecure.

However, I bit further down under the heading "Testing 3-D Secure authentication" is states that you can test 3D Secure with some codes *instead of* "password":

> To successfully authenticate the transaction, enter password into the password field during the 3-D Secure authentication process.
> 
> Alternatively you can enter E:N:06 into the password field to simulate the scenario where an error occurred during authentication and you will receive the 3-D Secure status: Error
> 
> Any other phrase will fail the authentication, allowing you to test your rules and 3D-Secure response handling.

So try that - E:N:06 in the password field.

I realise that page is a different API, but it does site on top of Direct, so it could just be that the Direct documentation has just not caught up yet. It's worth a try.

**Comment by beningreenjam** [comment]
Recently I added the `returnUrl` and `cancelUrl` parameters and discovered that after passing 3D Secure it was going into a redirect loop (silly me, I know as I forgot to add those required parameters in). Although now, I've just attempted a card number that should successfully authorise, the "E:N:06" password and it authorises fine. In fact any password now authorises it.

All other test cards are authorising regardless of 3D Secure status.

Just to confirm, are there any other URL-type parameters I need to include? Also, is the purpose of the 'returnUrl' parameter is exclusively for when the purchase is complete and showing a confirmation page to the use?

**Comment by judgej** [comment]
Hmm, we need to get to the bottom of whether Sage Pay is behaving differently, or OmniPay is not catching the status correctly.

I think returnUrl is overused somewhat, and can have many meanings. In this case, `returnUrl` given to the `DirectAuthorizeRequest` message is where 3DSecure will send the user back to when they have entered their password:

https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/Response.php#L84

I don't think 3DSecure has a concept of a separate "cancel" URL - it's the same return endpoint. The `DirectCompleteAuthorizeRequest` message is then used to capture the 3DSecure result on return to that URL (it sends the PaRes to Sage Pay, which then returns the final transaction result), with the `Response` message capturing the final status.

**Comment by beningreenjam** [comment]
Well it appears that the `returnUrl` parameter is what's affecting the outcome of 3D Secure, at least for cards that are supposed to authorise. Without that in place I'm back to getting "password is required" error message whatever password I enter, including "E:N:06". The other card numbers, including those meant to fail authorisation, are still authorising successfully.

When posting to the live gateway server, I'll still encounter a redirect loop for 3D Secure as I did before and no changes have been made from that commit.

**Comment by judgej** [comment]
I've been trying out this error code on the Sage Pay Integration REST API. Using `E:N:06` as the 3DSecure password results in this 3DSecure status result:

HTTP: 201
status: Error

If I then go ahead and fetch the transaction from Sage Pay anyway, I get this:

~~~php
BODY = Array
(
    [statusCode] => 0000
    [statusDetail] => The Authorisation was Successful.
    [transactionId] => CE1B5D44-0020-6D3C-FF3A-B8212FE5CE1F
    [transactionType] => Payment
    [retrievalReference] => 9763352
    [bankResponseCode] => 00
    [bankAuthorisationCode] => 999777
    [status] => Ok
    [3DSecure] => Array
        (
            [status] => Error
        )

)
~~~

The test gateway is telling me the transaction was successful, even though it failed 3DSecure and I told it to `Force` the 3DSecure rules.

That looks to me like the test gateway does not feed the 3DSecure result into the transaction overall result. Is this what you have been finding with the Direct gateway - a failed 3DSecure but still a successful payment or authorisation? I'll bring this up with Sage Pay now to see if I'm missing something.

**Comment by beningreenjam** [comment]
That does correspond with what I've been experiencing.

**Comment by judgej** [comment]
Cool - it's not just you then :-) I've asked the dev team, so we'll see what comes back.

**Comment by beningreenjam** [comment]
Although after reading your comment I decided to try leaving the apply3DSecure parameter as default and removing the returnUrl parameter, as had not done so before. It no longer attempts a 3D Secure authorisation at all, on any card. Something certainly feels wrong with SagePay in this case.

**Comment by Skizu** [comment]
Upon looking into this the issue seems to lay with the `Omnipay\SagePay\Message\Response` class, the `isSuccessful()` message inarticulately, the response returns a breakdown of it's checks, which you do not check for the `isSuccessful()` message:
```php
[
  "VPSProtocol" => "3.00"
  "Status" => "OK"
  "StatusDetail" => "0000 : The Authorisation was Successful."
  "VPSTxId" => "{00000000-0000-0000-0000-000000000000"
  "SecurityKey" => "0000000000"
  "TxAuthNo" => "0000000"
  "AVSCV2" => "ALL MATCH"
  "AddressResult" => "MATCHED"
  "PostCodeResult" => "MATCHED"
  "CV2Result" => "MATCHED"
  "3DSecureStatus" => "ERROR"
  "DeclineCode" => "00"
  "ExpiryDate" => "0116"
  "BankAuthCode" => "000000"
]
```

To get around this I can make a RP to make the check smarter, or you can handle it in your controller.

**Comment by judgej** [comment]
According to the Sage Pay documentation, a status of "OK" means all the fraud checks passed, including any 3DSecure rules that you chose to enforce. I think you should be seeing "REJECTED" here if you have Apply3DSecure=1

This is assuming we are understanding just what a 3DSecure status of "Error" actually means. It means that some upstream system is down, so 3DSecure could not be performed *at all*. It does not mean that the user failed to provide the correct password. Maybe in this case, Sage Pay give the transaction the "benefit of the doubt" and authorises the transaction anyway (though that feels wrong to me).

If Sage Pay returns an OK status, then your transaction **has** been authorised, regardless of what all the various other fraud prevention flags say. That's my understanding - does that contradict anything you have read?

**Comment by Skizu** [comment]
No that going on par with what I've read, only thing is regardless of `Apply3DSecure=1` all issues with 3D Secure will the message return an `OK` (assuming the rest of the message is valid). But I am not sure this is an issue? And if so it can be handled by the user implementation by checking the value of `3DSecureStatus` from the response.

**Comment by judgej** [comment]
My point is that regardless of the 3DSecure result, if the `Payment` transaction returns "OK" then you've taken the cash. If you choose to fail the transaction in the application due to the 3DSecure result, then you would need to provide a refund (or cancel the authorisation). That's why the status that OmniPay is returning, I believe, is correct, and should not be treated as a failed transaction in the application, even if you think it should be (I'm trying to get confirmation of this from Sage).

**Comment by judgej** [comment]
Hi @beningreenjam I have an answer for you. Basically, the test environment behaves slightly different to the live environment. This is from Sage Pay:

> Basically our test environment is not connected to any banks and as such we simulate the authorisation response. The simulator in test will alway authorise the transaction if you use valid test details. 

So you can test different transaction results based on the cards used. You can test various 3DSecure results based on the password entered. But in the test gateway, the two are NOT connected as they would be in live.

The situation may change, but that is how it is now. There is nothing omnipay-sagepay should do about this IMO, except perhaps for some notes in the documentation.

**Comment by beningreenjam** [comment]
Hey @judgej thanks for contacting them and forwarding their response on. It coincides with what I was starting to think anyway :+1:
