### ISSUE TITLE
Repeat payment support

### ISSUE THREAD

**Issue by coatesap** [thephpleague/omnipay-sagepay#56]
SagePay's repeat payment support is pretty simple and useful for subscription services, so I'm planning to submit a PR roughly based on #1 to add this functionality. 

I'm keen to do this in a gateway-agnostic fashion (in terms of what parameters are set on the request). Is anyone aware of any other Omnipay drivers that support repeat billing so that I can see if there are any standards (naming conventions, etc) already in place for this?

**Comment by delatbabel** [comment]
The Stripe and PayPal gateway plugins have the most complete subscription service support, AFAIK. Basing your plugin on one of those would be preferable, however it should be noted that every gateway does subscription support very differently so you should code whatever works for your gateway.

**Comment by judgej** [comment]
@delatbabel Just a note that Sage Pay's repeat billing is not a subscription service in the strictest sense. It is closer to using a card token to make customer-not-present payments, but using the card details stored in a past transaction on the Sage Pay servers rather than using a card token. I believe at this stage Sage Pay are not allowed to hold CVV details, so either a non-CVV repeat payment can be made (necessary if automating a regular payment in the merchant site, but with less merchant protection) or a new CVV can be passed in if the customer is present (e.g if buying from a shop or manually paying an invoice).

**Comment by judgej** [comment]
It seems like a crazy system TBH - each further payment you take gives you another transaction that can support repeat payments. It's not like there is just a single card token for a given credit card hanging around for a single site at any one time that can be used, revoked, inspected etc.
