### ISSUE TITLE
Repeat Direct Payments

### ISSUE THREAD

**Issue by dmnc** [thephpleague/omnipay-sagepay#58]
I'd like to add support for repeat payments.

This uses `RelatedVendorTxCode`, `RelatedVPSTxId`, `RelatedSecurityKey`, `RelatedTxAuthNo` in exactly the same way the refund does.

Before I do that, I'd like to get your input on which way you'd prefer this to be done. I see two options:
1. Create new request for repeat. So `DirectAuthorizeRepeatRequest` and  `DirectPurchaseRepeatRequest` etc.
2. Make the `DirectAuthorizeRequest` and  `DirectPurchseRequest` able to accept a `transactionReference` like `RefundRequest` does.

Option 1 would obviously be most stand alone but I think 2 probably fits most into the spirit of Omnipay with the way this has been done in, for example, Stripe.

@judgej let me know which you'd prefer and I'll get on with it and open a PR.

**Comment by kayladnls** [comment]
I think it makes more sense to allow the related data to be sent as part of the `DirectAuthorizeRequest` and `DirectPurchaseRequest` (option 2). As you mentioned other gateways are already doing this method.

**Comment by dmnc** [comment]
Perfect. I'll go with that approach.

**Comment by judgej** [comment]
:+1:

**Comment by coatesap** [comment]
Support has been added for this in PR #66, which is now merged into master, so this issue should now be closed.

**Comment by judgej** [comment]
The version in PR #66 takes the other approach: creating a new message for repeat payments rather than piggy-backing on the existing `DirectPurchase` giving us a `$gateway->repeatPayment()` method.

Q: should that have been `repeatPurchase()` to keep the OmniPay terminology?  
Q: does a `repeatAuthorize()` make any sense here?

**Comment by judgej** [comment]
Sage Pay supports both a `REPEAT` and `REPEATDEFERRED` transaction type. This translates to an OmniPay `Purchase` and `Authorize`, but using the saved credit card details of the previous transaction. So:

a) A repeat payment is not the whole story - we have repeat authorisations too, that need to be released (captured) later.
b) Since we have repeat authorisations, that would presumably be called `repeatAuthorize` then it makes sense for the authorize+capture to be `repeatPurchase` (OmniPay terminology) rather than `repeatPayment` (Sage Pay terminology).

The currency is also hard-coded in PR #66 to `GBP` and that certainly needs to change.

In addition, many of the details in the original transaction can be changed for the repeat transaction, for example a different delivery address (but not customer details, since they are linked to the card), or a new basket (needed if the repeat amount is different, or if needing to sync the basket with a back-end accounting package). I think those items need to be supported by the repeat transaction.

PS #66 may be working in production, but it is limited in scope so works in a very specific environment, and IMO needs to be extended a little. What is there is fine so far, so there is no need to revert, but I would deprecate `repeatPayment()` for `repeatPurchase()`.

**Comment by judgej** [comment]
Some of the features of PR #60 could be merged in with PR #66. For example, if calling Direct `purchase()` with a previous `transactionReference` then there is no reason why it can't return a `DirectRepeatPurchase` message automatically, instead of a `DirectPurchase` message. So we could have the best of both worlds. Keeping them as separate messages (purchase and repeatPurchase) makes sense due to the different set of parameters that are supported or are required vs optional.

**Comment by judgej** [comment]
I've created a PR to cover some of the above points. It does not yet include the addition fields that REPEAT and REPEATDEFERRED support (new shipping address and ItemBag/cart/basket).

**Comment by judgej** [comment]
So, PR #66 + PR #68 covers everything PR #60 covered. It does *not* extend `DirectAuthorizeRequest` and `DirectPurchaseRequest` because it supports a smaller subset of the parameters that those messages support. It provides `repeatAuthorize` and `repeatPurchase`.

Feel free to try it out and give feedback - hopefully we can get a release number fore this soon, as there is a backlog of other changes to go in.

**Comment by judgej** [comment]
`transactionReference` needs to go in as an alias for `relatedTransactionReference`, with the latter deprecated.

**Comment by judgej** [comment]
Don't know how I missed it, but there are four other `related*` methods there too. I should do the same with those.

**Comment by judgej** [comment]
In release [2.4.0](https://github.com/thephpleague/omnipay-sagepay/releases/tag/2.4.0)
