### ISSUE TITLE
Support for SagePay token system

### ISSUE THREAD

**Issue by ntsim** [thephpleague/omnipay-sagepay#61]
Having recently used Omnipay for a SagePay integration, there currently isn't token support baked in with this package for the SagePay token system that is detailed [here](http://www.sagepay.co.uk/support/12/36/sage-pay-token-system-understanding-the-process) and [here](http://www.sagepay.co.uk/file/12256/download-document/TOKEN_SYSTEM_Integration_and_Protocol_Guidelines_010814.pdf?token=-cTswXTX1ouoe_94rUj8n_p9PYvt68feSFBdjMYJPMA). Consequently, I had to go about piggybacking off some of the current functionality to implement this.

I can appreciate if this isn't a mission critical component to have, but it would be good to know if this would be a feature that might be implemented in the future, maybe with your 3.0 release?

**Comment by judgej** [comment]
Every improvement will be mission critical to *someone* :-)

If you have forked the repository to make your changes, then push it back to github and we can look at turning it into a pull request. Practical experience like yours of features in production is what helps to drive this project forwards.

This does sound like a great feature to use though. Repeat purchases and customer loyalty are a big boom to online shops and services.

------

So down to the technicalities. A token can be registered either through a token creation transaction, or on the back of a full transaction. The latter method will involve the fewest changes - just adding a new flag in the transaction registration. That would be a good start. We would also use a new getter to return the token from the transaction result (in the notification callback for Sage Pay Server).

Using the token will be a bit more fiddly for OmniPay 2.x The token is supplied instead of a card number. The CVV is still required, so that could mean modifying the `CreditCard` class to allow this. I have a feeling that may already have been done for other gateways, so it will be worth looking at how they handle it.

**Comment by ntsim** [comment]
I'll setup a pull request with what i've done so far as soon as I can, it's been centred around the Server integration so will need some additional tuning for Direct, although I doubt there'll be major differences.

In terms of the actual usage of the token, I don't quite understand the need to modify the `CreditCard` itself? Would it not be easier to just conditionally replace components of the request data based on if a token was also passed through to the `Direct/ServerAuthorizeRequest`?

**Comment by judgej** [comment]
The credit card class is in core OmniPay and contains a certain amount of validation. If a card is not set, then it could possibly report the details it has been given as invalid. I need to look into it a bit more though, because I know things have changed there.

**Comment by dmnc** [comment]
Just going to jump in because I looked at this very recently for #60 which needs customer details but not card details.

The validate method on the card only checks card number and expiry. It does not validate the customer details (address, name etc.) or, surprisingly, CVV.

Unless I am missing something, this means that there is currently no validation on CVV within Omnipay so you should be fine to just avoid calling `$this->getCard()->validate()` on the request.

You will still want to call `$this->validate('card')` to make sure some details are provided though.

**Comment by judgej** [comment]
Ping @judgej - reminder to self to look at this stuff!

**Comment by llincoln** [comment]
Hi Folks, I've not been involved in this project directly before but this issue has been of particular interest to me for a production setting. I have created a fork here:

https://github.com/llincoln/omnipay-sagepay

Ci Build is here:

https://travis-ci.org/llincoln/omnipay-sagepay

I extended the Server Integration Method classes with some minor modifications and introduced the relevant unit tests.

And example of this in implementation can be found here:

The sample web app is plugged into a sagepay test environment (so may be subject to unplugging in the near future)

http://wales-surfing.co.uk/omnipay/

The source for the sample web app can be found here:

https://github.com/llincoln/omnipay-fuel-sample

I've not even thought about setting it up for Direct Method yet however I thought this might help someone out there.
